### ISSUE TITLE
Scrape Google

### ISSUE THREAD

**Issue by mattmotoki** [HACC2018/ohia.ai#16]
Scrape Google for images of plants on the following lists:
* [Native Plants](https://drive.google.com/file/d/1lIs8638gBxmWgDSTc84gnGSSHgMsyYXs/view)
* [Invasive Plants](http://www.oahuisc.org/target-pests/)
* Common Plants
   - hibiscus
   - plumeria
   - pineapple
   - ginger
   - anthurium
   - heliconia
   - bougainvillea

Upload all data to our shared [images directory](https://drive.google.com/drive/u/1/folders/1lgRqxc8dWflkXn8a2dRB8GBswCe_bZpZ).

**Comment by mattmotoki** [comment]
Tasks:
* download/scrape images of plants
* collect meta data; e.g., stories, uses, taxonomic data, status (native, invasive, endangered, etc.)
* filter out all non-plant images

All the plants on this list: http://www.oahuisc.org/target-pests/

**Comment by sorapk** [comment]
uploaded additional 300 -  400 images per common genus, under "sora img"
