### ISSUE TITLE
Implement the Identifier Results page

### ISSUE THREAD

**Issue by mrbarbasa** [HACC2018/ohia.ai#23]
- [x] Implement frontend layout and styling
- [x] Implement logic to interface with backend

**Comment by spjy** [comment]
Design is complete unless others have feedback. Just need to hook into database now, waiting on #39.

**Comment by mrbarbasa** [comment]
@spjy I need to work on this next, much of the database hookup relies on the results of the image upload. Thanks for implementing the frontend for this!
