### ISSUE TITLE
Create TensorFlow JS model to do inference

### ISSUE THREAD

**Issue by mattmotoki** [HACC2018/ohia.ai#5]
Setup a TensorFlowJS model to do inference in the browser
* load pretrained weights
* make predictions on new images

**Comment by rohit-basavaraju** [comment]
Looks like there are streamlined steps to export keras model written in python to tensorflow.js! https://js.tensorflow.org/tutorials/import-keras.html

**Comment by mrbarbasa** [comment]
Related to #29.
