### ISSUE TITLE
Set up the Vue.js and Quasar frontend to display a home page

### ISSUE THREAD

**Issue by mrbarbasa** [HACC2018/ohia.ai#8]
Learn:
- https://vuejs.org/v2/guide/
- https://quasar-framework.org/

Notes:
- Create a folder called `frontend` and place all the code there. You may add a separate `package.json` file within it, if necessary.
- The home page can be empty for now.

**Comment by spjy** [comment]
#12 Added a "frontend" folder containing Quasar. #

**Comment by mrbarbasa** [comment]
The name "client" sounds good, thanks @spjy for setting this up! Resolved by commit: https://github.com/HACC2018/ohia.ai/commit/c5fae5c314a8e2878f7424b0b6178b0d584ac496
